owner: Howielyn
repo: Cloud-Status

sites:
  - name: Catbox Litterbox
    url: https://litterbox.catbox.moe

  - name: Google Drive
    url: https://drive.google.com
status-website:
  theme: light
  css: "nav { display: none }"
  favicon: 
  faviconSvg: 
  baseUrl: /Cloud-Status
  logoUrl: 
  name: Cloud-Status

i18n:
  footer: Powered by Upptime.
